<ul class="form-list" id="payment_form_paymentwall_pwbrick" style="display: none">
    <li>
        <label for="paymentwall_pwbrick_cc_type" class="required"><em>*</em><?php echo $this->__('Card Type') ?></label>

        <div class="input-box">
            <select id="paymentwall_pwbrick_cc_type" name="payment[cc_type]"
                    title="<?php echo $this->__('Card Type') ?>"
                    class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option
                        value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>>
                        <?php echo $_typeName ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="paymentwall_pwbrick_cc_number" class="required">
            <em>*</em>
            <?php echo $this->__("Card Number") ?>
        </label>

        <div class="input-box">
            <input name="payment[cc_number]" type="text" autocomplete="off" id="paymentwall_pwbrick_cc_number"
                   class="input-text validate-cc-number validate-cc-type" data-brick="card-number"/>
        </div>
    </li>
    <li>
        <label for="paymentwall_pwbrick_expiration" class="required">
            <em>*</em>
            <?php echo $this->__("Card expiration"); ?>
        </label>

        <div class="input-box">
            <input name="payment[cc_exp_month]" type="text" id="paymentwall_pwbrick_expiration" autocomplete="off"
                   class="month validate-cc-exp required-entry" data-brick="card-expiration-month" placeholder="MM"
                   maxlength="2" size="2"/> /
            <input name="payment[cc_exp_year]" type="text" id="paymentwall_pwbrick_expiration_yr" autocomplete="off"
                   class="year required-entry" data-brick="card-expiration-year" placeholder="YY" maxlength="4"
                   size="4"/>
        </div>
    </li>
    <li>
        <label for="paymentwall_pwbrick_cc_cid" class="required">
            <em>*</em>
            <?php echo $this->__("Card CVV") ?>
        </label>

        <div class="input-box">
            <input name="payment[cc_cid]" type="text" id="paymentwall_pwbrick_cc_cid" autocomplete="off"
                   class="input-text cvv required-entry validate-cc-cvn"
                   data-brick="card-cvv" maxlength="4"/>
        </div>
        <div class="no-display">
            <input type="hidden" name="payment[brick_token]" id="paymentwall_pwbrick_token">
            <input type="hidden" name="payment[brick_fingerprint]" id="paymentwall_pwbrick_fingerprint">
        </div>
    </li>
</ul>
<script type="text/javascript">
    var brick = PW.initPwBrick('<?php echo $this->getPublicKey(); ?>');
    PW.rewriteSavePayment(brick);
</script>
